ALTER TABLE module
    ALTER COLUMN module SET DATA TYPE VARCHAR (32);

ALTER TABLE permission
    ALTER COLUMN node SET DATA TYPE VARCHAR (32);

ALTER TABLE prefix
    ALTER COLUMN prefix SET DATA TYPE VARCHAR (32);
