CREATE TABLE osu_beatmap
(
    approved            INT          NOT NULL,
    submitDate          BIGINT DEFAULT NULL,
    approvedDate        BIGINT DEFAULT NULL,
    lastUpdate          BIGINT DEFAULT NULL,
    artist              VARCHAR(256) NOT NULL,
    beatmapId           INT          NOT NULL,
    beatmapsetId        INT          NOT NULL,
    bpm                 FLOAT        NOT NULL,
    creatorName         VARCHAR(256) NOT NULL,
    creatorId           INT          NOT NULL,
    difficultyRating    FLOAT        NOT NULL,
    difficultyAim       FLOAT        NOT NULL,
    difficultySpeed     FLOAT        NOT NULL,
    difficultySize      FLOAT        NOT NULL,
    difficultyOverall   FLOAT        NOT NULL,
    difficultyApproach  FLOAT        NOT NULL,
    difficultyDrain     FLOAT        NOT NULL,
    hitLength           INT          NOT NULL,
    source              VARCHAR(256) NOT NULL,
    genre               INT          NOT NULL,
    language            INT          NOT NULL,
    title               VARCHAR(256) NOT NULL,
    totalLength         INT          NOT NULL,
    version             VARCHAR(256) NOT NULL,
    fileMd5             CHAR(32)     NOT NULL,
    mode                INT          NOT NULL,
    tags                VARCHAR(256) NOT NULL,
    favouriteCount      INT          NOT NULL,
    rating              FLOAT        NOT NULL,
    playCount           INT          NOT NULL,
    passCount           INT          NOT NULL,
    countNormal         INT          NOT NULL,
    countSlider         INT          NOT NULL,
    countSpinner        INT          NOT NULL,
    maxCombo            INT          NOT NULL,
    downloadUnavailable TINYINT      NOT NULL,
    audioUnavailable    TINYINT      NOT NULL,
    PRIMARY KEY (beatmapId)
);
