CREATE TABLE osu_beatmap
(
    approved             INT           NOT NULL,
    submit_date          BIGINT DEFAULT NULL,
    approved_date        BIGINT DEFAULT NULL,
    last_update          BIGINT DEFAULT NULL,
    artist               VARCHAR(256)  NOT NULL,
    beatmap_id           INT           NOT NULL,
    beatmapset_id        INT           NOT NULL,
    bpm                  FLOAT         NOT NULL,
    creator_name         VARCHAR(256)  NOT NULL,
    creator_id           INT           NOT NULL,
    difficulty_rating    FLOAT         NOT NULL,
    difficulty_aim       FLOAT         NOT NULL,
    difficulty_speed     FLOAT         NOT NULL,
    difficulty_size      FLOAT         NOT NULL,
    difficulty_overall   FLOAT         NOT NULL,
    difficulty_approach  FLOAT         NOT NULL,
    difficulty_drain     FLOAT         NOT NULL,
    hit_length           INT           NOT NULL,
    source               VARCHAR(256)  NOT NULL,
    genre                INT           NOT NULL,
    language             INT           NOT NULL,
    title                VARCHAR(256)  NOT NULL,
    total_length         INT           NOT NULL,
    version              VARCHAR(256)  NOT NULL,
    file_md5             VARCHAR(32)   NOT NULL,
    mode                 INT           NOT NULL,
    tags                 VARCHAR(1000) NOT NULL,
    favourite_count      INT           NOT NULL,
    rating               FLOAT         NOT NULL,
    play_count           INT           NOT NULL,
    pass_count           INT           NOT NULL,
    count_normal         INT           NOT NULL,
    count_slider         INT           NOT NULL,
    count_spinner        INT           NOT NULL,
    max_combo            INT           NOT NULL,
    download_unavailable BOOLEAN       NOT NULL,
    audio_unavailable    BOOLEAN       NOT NULL,
    PRIMARY KEY (beatmap_id)
);
